In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cust = pd.read_csv('DIM_CUSTOMERS.csv')
order = pd.read_csv('FACT_ORDERS.csv')

In [ ]:
#INITIAL CHECK OF DATA

In [18]:
cust.head(5)

,cust_id,customer_name,email,phone,customer_type,city,state,country,age,registration_date,loyalty_tier,preferred_destination
0,C0001,Customer 1,customer1@email.com,555-1000001,Registered,New York,NY,France,33,2023-04-03,Bronze,Tokyo
1,C0002,Customer 2,customer2@email.com,555-1000002,Registered,Singapore,NY,Singapore,45,2022-03-07,Bronze,Tokyo
2,C0003,Customer 3,customer3@email.com,555-1000003,Registered,London,NaN,Singapore,56,2022-02-24,Gold,Bangkok
3,C0004,Customer 4,customer4@email.com,555-1000004,Registered,Singapore,DXB,UK,46,2023-07-24,Bronze,Bangkok
4,C0005,Customer 5,NaN,555-1000005,Guest,Dubai,IDF,France,27,2023-03-17,Silver,Tokyo

In [19]:
order.head(5)

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
0,ORD00001,C0040,2024-08-17,2025-04-21,London,Luxury,Mobile App,1,4150,195,Cancelled,Bank Transfer,Bob,14
1,ORD00002,C0110,2025-09-28,2026-09-21,Bangkok,Standard,Agent,3,4795,7,Completed,UPI,Charlie,7
2,ORD00003,C0090,2024-07-04,2025-05-27,Bangkok,Luxury,Mobile App,1,250,36,Pending,Bank Transfer,Alice,3
3,ORD00004,C0192,2024-08-08,2026-01-21,Dubai,Premium,Mobile App,0,4545,94,Cancelled,Bank Transfer,Charlie,14
4,ORD00005,C0146,2024-02-23,2025-06-09,Paris,Luxury,Website,1,895,69,Cancelled,Bank Transfer,Dana,9

In [20]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            801 non-null    object
 1   customer_id         801 non-null    object
 2   booking_date        801 non-null    object
 3   travel_date         801 non-null    object
 4   destination         801 non-null    object
 5   package_type        801 non-null    object
 6   booking_channel     801 non-null    object
 7   quantity            801 non-null    int64
 8   booking_amount      801 non-null    int64
 9   discount_amount     801 non-null    int64
 10  booking_status      801 non-null    object
 11  payment_method      801 non-null    object
 12  agent_name          801 non-null    object
 13  trip_duration_days  801 non-null    int64
dtypes: int64(4), object(10)
memory usage: 87.7+ KB

In [21]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cust_id                201 non-null    object
 1   customer_name          201 non-null    object
 2   email                  200 non-null    object
 3   phone                  201 non-null    object
 4   customer_type          201 non-null    object
 5   city                   201 non-null    object
 6   state                  162 non-null    object
 7   country                201 non-null    object
 8   age                    201 non-null    int64
 9   registration_date      201 non-null    object
 10  loyalty_tier           201 non-null    object
 11  preferred_destination  201 non-null    object
dtypes: int64(1), object(11)
memory usage: 19.0+ KB

In [27]:
order.shape

(801, 14)

In [26]:
cust.shape

(201, 12)

In [ ]:
# FOR MISSING VALUES IN DATA

In [28]:
order.isnull().sum()

order_id              0
customer_id           0
booking_date          0
travel_date           0
destination           0
package_type          0
booking_channel       0
quantity              0
booking_amount        0
discount_amount       0
booking_status        0
payment_method        0
agent_name            0
trip_duration_days    0
dtype: int64

In [29]:
cust.isnull().sum()

cust_id                   0
customer_name             0
email                     1
phone                     0
customer_type             0
city                      0
state                    39
country                   0
age                       0
registration_date         0
loyalty_tier              0
preferred_destination     0
dtype: int64

In [30]:
order.duplicated().sum()

np.int64(1)

In [31]:
cust.duplicated().sum()

np.int64(1)

In [34]:
order[order.duplicated(keep=False)]

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
99,ORD00100,C0004,2024-07-13,2025-05-01,Dubai,Standard,Agent,5,1935,180,Completed,UPI,Bob,10
800,ORD00100,C0004,2024-07-13,2025-05-01,Dubai,Standard,Agent,5,1935,180,Completed,UPI,Bob,10

In [35]:
cust[cust.duplicated(keep=False)]

,cust_id,customer_name,email,phone,customer_type,city,state,country,age,registration_date,loyalty_tier,preferred_destination
19,C0020,Customer 20,customer20@email.com,555-1000020,Guest,New York,IDF,UAE,28,2024-07-18,Bronze,Rome
200,C0020,Customer 20,customer20@email.com,555-1000020,Guest,New York,IDF,UAE,28,2024-07-18,Bronze,Rome

In [ ]:
#REMOVING DUPLICATES

In [39]:
order_Clean = order.drop_duplicates().copy()

In [40]:
cust_Clean = cust.drop_duplicates().copy()

In [41]:
order_Clean.head()

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
0,ORD00001,C0040,2024-08-17,2025-04-21,London,Luxury,Mobile App,1,4150,195,Cancelled,Bank Transfer,Bob,14
1,ORD00002,C0110,2025-09-28,2026-09-21,Bangkok,Standard,Agent,3,4795,7,Completed,UPI,Charlie,7
2,ORD00003,C0090,2024-07-04,2025-05-27,Bangkok,Luxury,Mobile App,1,250,36,Pending,Bank Transfer,Alice,3
3,ORD00004,C0192,2024-08-08,2026-01-21,Dubai,Premium,Mobile App,0,4545,94,Cancelled,Bank Transfer,Charlie,14
4,ORD00005,C0146,2024-02-23,2025-06-09,Paris,Luxury,Website,1,895,69,Cancelled,Bank Transfer,Dana,9

In [42]:
cust_Clean.head()

,cust_id,customer_name,email,phone,customer_type,city,state,country,age,registration_date,loyalty_tier,preferred_destination
0,C0001,Customer 1,customer1@email.com,555-1000001,Registered,New York,NY,France,33,2023-04-03,Bronze,Tokyo
1,C0002,Customer 2,customer2@email.com,555-1000002,Registered,Singapore,NY,Singapore,45,2022-03-07,Bronze,Tokyo
2,C0003,Customer 3,customer3@email.com,555-1000003,Registered,London,NaN,Singapore,56,2022-02-24,Gold,Bangkok
3,C0004,Customer 4,customer4@email.com,555-1000004,Registered,Singapore,DXB,UK,46,2023-07-24,Bronze,Bangkok
4,C0005,Customer 5,NaN,555-1000005,Guest,Dubai,IDF,France,27,2023-03-17,Silver,Tokyo

In [43]:
# FOR STANDARDIZING TEXT

In [47]:
cust_Clean[["customer_type", "city"]] = cust_Clean[["customer_type", "city"]].apply(
    lambda col: col.str.strip().str.title()
)

In [48]:
order_Clean[["destination", "booking_channel"]] = order_Clean[["destination", "booking_channel"]].apply(
    lambda col: col.str.strip().str.title()
)

In [49]:
cust_Clean["customer_type"].value_counts()

customer_type
Registered    160
Guest          40
Name: count, dtype: int64

In [50]:
order_Clean["destination"].value_counts()

destination
Tokyo      175
Paris      164
Dubai      161
London     152
Bangkok    148
Name: count, dtype: int64

In [51]:
cust_Clean["city"].value_counts()

city
New York     47
Dubai        46
Singapore    42
Paris        34
London       31
Name: count, dtype: int64

In [52]:
#HANDLING MISSING VALUES

In [54]:
cust_Clean.isnull().sum().sum()

np.int64(40)

In [55]:
order_Clean.isnull().sum().sum()

np.int64(0)

In [56]:
cust_Clean["phone"] = cust_Clean["phone"].fillna("Unknown")

In [57]:
cust_Clean["city"] = cust_Clean["city"].fillna("Unknown")

In [59]:
order_Clean["booking_channel"] = (
    order_Clean["booking_channel"]
    .fillna("Unknown")
)

In [60]:
#CHECKING OUTLIERS

In [61]:
cust_Clean["age"].describe()

count    200.000000
mean      52.155000
std       69.285231
min       18.000000
25%       34.000000
50%       46.000000
75%       63.000000
max      999.000000
Name: age, dtype: float64

In [65]:
cust_clean[(cust_Clean["age"] > 100) | (cust_Clean["age"] <= 0)]

,cust_id,customer_name,email,phone,customer_type,city,state,country,age,registration_date,loyalty_tier,preferred_destination
9,C0010,Customer 10,customer10@email.com,555-1000010,Guest,Dubai,IDF,UK,999,2023-12-29,Bronze,Rome

In [67]:
median_age = cust_Clean.loc[
    cust_Clean["age"] < 100,
    "age"
].median()

cust_Clean.loc[
    cust_Clean["age"] > 100,
    "age"
] = median_age

In [69]:
order_Clean[
    order_Clean["booking_amount"] < 0
]

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
10,ORD00011,C0112,2024-09-06,2026-03-23,Bangkok,Premium,Agent,1,-500,101,Cancelled,Bank Transfer,Charlie,5

In [70]:
order_Clean[
    (order_Clean["booking_status"] == "Completed")
    &
    (order_Clean["booking_amount"] <= 0)
]

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
20,ORD00021,C0080,2024-05-12,2026-09-02,Tokyo,Premium,Agent,4,0,164,Completed,Card,Alice,12

In [78]:
order_Clean[
    order_Clean["quantity"] == 0
]

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,booking_status,payment_method,agent_name,trip_duration_days
3,ORD00004,C0192,2024-08-08,2026-01-21,Dubai,Premium,Mobile App,0,4545,94,Cancelled,Bank Transfer,Charlie,14

In [79]:
order_Clean["booking_date"] = pd.to_datetime(
    order_Clean["booking_date"],
    errors="coerce"
)

In [80]:
order_Clean["travel_date"] = pd.to_datetime(
    order_Clean["travel_date"],
    errors="coerce"
)

In [81]:
set(
    order_Clean["customer_id"]
) - set(
    cust_Clean["cust_id"]
)

{'C9050', 'C9150', 'C9250', 'C9350', 'C9450'}

In [82]:
orphan_ids = set(
    order_Clean["customer_id"]
) - set(
    cust_Clean["cust_id"]
)

print(orphan_ids)

{'C9150', 'C9050', 'C9250', 'C9350', 'C9450'}

In [83]:
merged_df = pd.merge(
    order_Clean,
    cust_Clean,
    left_on="customer_id",
    right_on="cust_id",
    how="left"
)

In [84]:
merged_df[
    merged_df["cust_id"].isna()
]

,order_id,customer_id,booking_date,travel_date,destination,package_type,booking_channel,quantity,booking_amount,discount_amount,...,email,phone,customer_type,city,state,country,age,registration_date,loyalty_tier,preferred_destination
49,ORD00050,C9050,2025-10-17,2026-08-25,Paris,Standard,Mobile App,5,4716,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,ORD00150,C9150,2024-08-11,2026-03-16,Paris,Premium,Mobile App,3,3458,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,ORD00250,C9250,2025-05-08,2025-12-21,Dubai,Standard,Agent,5,2236,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,ORD00350,C9350,2024-01-13,2025-05-05,Paris,Premium,Mobile App,2,3325,188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,ORD00450,C9450,2025-09-10,2025-06-28,Bangkok,Luxury,Website,4,1113,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
order_Clean.groupby(
    "destination"
)["booking_amount"].sum()

destination
Bangkok    390729
Dubai      400539
London     403458
Paris      420242
Tokyo      458426
Name: booking_amount, dtype: int64

In [87]:
order_Clean["booking_channel"].value_counts()

booking_channel
Agent         292
Website       262
Mobile App    246
Name: count, dtype: int64

In [88]:
order_Clean["booking_amount"].mean()

np.float64(2591.7425)

In [89]:
cust_Clean.to_csv(
    "DIM_CUSTOMERS_CLEAN.csv",
    index=False
)

In [90]:
order_Clean.to_csv(
    "FACT_ORDERS_CLEAN.csv",
    index=False
)

In [91]:
pip install mysql-connector-python sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   -- ------------------------------------- 1.0/17.7 MB 11.7 MB/s eta 0:00:02
   -- ------------------------------------- 1.0/17.7 MB 11.7 MB/s eta 0:00:02
   --- ------------------------------------ 1.6/17.7 MB 2.7 MB/s eta 0:00:07
   ------- -------------------------------- 3.1/17.7 MB 4.7 MB/s eta 0:00:04
   ------- -------------------------------- 3.1/17.7 MB 4.7 MB/s eta 0:00:04
   ------------- -------------------------- 5.8/17.7 MB 4.9 MB/s eta 0:00:03
   ---------------- ----------------------- 7.3/17.7 MB 5.5 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 5.8 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 7.6 MB/s eta 0:00:01
   ------------------------------ --------- 13.6/17.7 MB 7.6 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 6.9 MB/s  0:00:02
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql, mysql-connector-python

   ---------------------------------------- 0/2 [pymysql]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   ---------------------------------------- 2/2 [mysql-connector-python]

Successfully installed mysql-connector-python-9.7.0 pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Js1019_Surya@localhost/travel_analytics"
)

In [2]:
import pandas as pd

test = pd.read_sql(
    "SELECT DATABASE();",
    con=engine
)

print(test)

         DATABASE()
0  travel_analytics

In [3]:
import pandas as pd

orders = pd.read_csv("FACT_ORDERS.csv")
cust = pd.read_csv("DIM_CUSTOMERS.csv")

In [4]:
orders_clean = orders.drop_duplicates().copy()
cust_clean = cust.drop_duplicates().copy()

In [5]:
cust_clean.to_sql(
    name="dim_customers",
    con=engine,
    if_exists="replace",
    index=False
)

200

In [6]:
orders_clean.to_sql(
    name="fact_orders",
    con=engine,
    if_exists="replace",
    index=False
)

800

In [8]:
pd.read_sql("SELECT DATABASE();", engine)

         DATABASE()
0  travel_analytics

In [10]:
query = """
SELECT
    c.customer_name,
    o.destination,
    o.booking_amount
FROM fact_orders o
JOIN dim_customers c
ON o.customer_id = c.cust_id
LIMIT 10"""
result = pd.read_sql(query, engine)

print(result)

  customer_name destination  booking_amount
0   Customer 40      London            4150
1  Customer 110     Bangkok            4795
2   Customer 90     Bangkok             250
3  Customer 192       Dubai            4545
4  Customer 146       Paris             895
5  Customer 156       Paris            3821
6  Customer 171       Dubai            2726
7   Customer 66       Tokyo            2571
8  Customer 144       Tokyo            3101
9  Customer 104       Dubai            3621

In [11]:
pd.read_sql("SHOW TABLES;", engine)

  Tables_in_travel_analytics
0              dim_customers
1                fact_orders